FROM python:3.9

RUN mkdir data
RUN mkdir data/twitter
COPY twitter_processor.py .
COPY kafka_functions.py .
COPY secrets_docker.env secrets.env
COPY requirements.txt .
RUN pip3 install -r requirements.txt

CMD ["python3", "-u", "twitter_processor.py"]