FROM python:3.9

RUN mkdir data
RUN mkdir data/binance
COPY requirements.txt .
COPY binance_processor.py .
COPY kafka_functions.py .
COPY secrets_docker.env secrets.env
RUN pip3 install -r requirements.txt

CMD ["python3", "-u", "binance_processor.py"]