FROM python:3.9

COPY binance_producer.py .
COPY requirements.txt .
COPY secrets_docker.env secrets.env
COPY kafka_functions.py .
RUN pip3 install -r requirements.txt

CMD ["python3", "-u", "binance_producer.py"]