FROM python:3.9


RUN mkdir data
RUN mkdir data/binance
COPY binance_consumer.py .
COPY secrets.env .
COPY requirements.txt . 
COPY zmq_functions.py .

RUN pip3 install -r requirements.txt
CMD ["python3", "-u", "binance_consumer.py"]