version: '3'

services:
  binance_producer:
    container_name: binance_producer1
    hostname: binance_producer
    # image: zmq_binance_producer
    build:
      dockerfile: DockerFile.binance_producer
    ports: 
      - "5555:5555"
    expose:
      - "5556"
  binance_consumer:
    container_name: binance_consumer_1
    # image: zmq_binance_consumer
    build:
      dockerfile: DockerFile.binance_consumer
    depends_on:
      - binance_producer
    volumes:
      - ./data/binance:/data/binance
  twitter_producer:
    container_name: twitter_producer1
    hostname: twitter_producer
    # image: zmq_twitter_producer
    build:
      dockerfile: DockerFile.twitter_producer
    ports:
      - "5557:5557"
    expose:
      - "5558"
  twitter_consumer:
    container_name: twitter_consumer1
    # image: zmq_twitter_consumer
    build:
      dockerfile: DockerFile.twitter_consumer
    depends_on:
      - twitter_producer
    volumes:
      - ./data/twitter:/data/twitter