FROM python:3.9

COPY requirements.txt . 
RUN pip3 install -r requirements.txt
RUN mkdir data
COPY pe.py .
COPY kafka_functions.py .
COPY secrets_docker.env secrets.env

CMD ["python3", "-u", "pe.py"]